### ISSUE TITLE
compiling failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#847]
Hello,
When I want to compile on Ubuntu 16.04, I encounter this error:
`[131/134] cc: src/examples/xiphos-nav.c -> build/default/src/examples/xiphos-nav_1.o`
`../src/gnome2/utilities.c: In function ‘xiphos_open_default’:`
`../src/gnome2/utilities.c:1448:66: error: expected expression before ‘/’ token`
`  gtk_show_uri(NULL, file, gtk_get_current_event_time(), &error);*/`
`                                                                 ^`
`Waf: Leaving directory /home/cyrille/Documents/github/xiphos/build'`
`Build failed:  -> task failed (err #1): `
`	{task: cc utilities.c -> utilities_2.o}`

Thank you.
